language: node_js
node_js: 11.10.0
os:
- linux
before_script:
- npm install -g gulp
script: gulp

cache:
  directories:
    - "node_modules"

before_deploy:
  - pwd
  - ls dist/js/
  
deploy:
  provider: releases
  api_key:
    secure: "fvnsZGsr14eEEl9KHiqy5eyfeBGbKDBesxoIInxFJwVei24iUVUrVGJvJ3VPQ7WMvtXsQ17FxOyREt4RfkKnfh+Y7BtxK7maMEqcvG+ARdY/1QjEQoZkPmFoaGBb7mxv5FPNczr+UsBYYU4cxq7SguFdGFq/xSN3cD/kXhgsShJ6YblB6RvcYYB9VddNiFnZD+2ouI3nTLM+WAkoHgikm1XVSWdfTAP1NkyARXydEs9Ml5RIH6aqK7sbW4fz3froZfPN46KvuOCfOlN/lmqiJiMCOgV25O6zHZPLHCfpdqbquPxAHd6AvDBHYdzbV6xiVYiDQm+82dAGOPdO8kw0Gv2Ch6gGwh2t+nvbxvdzNVmjRGrlrtOTq6F5AVtsb/51NI0Mnf3NUyl3TvhIRKohj0fSNw3UsGzg+7rSWE4iMrT7fdkkJrfGkYkF6q7+GPiyZFTdCa3f9fITVGblCXH6a99szHoV6wxWlkpIzv7itoP6cnMtkazNZ4ojVuSBAbIiyggnEZrEj/DL2eB9NMT9fIC80w+zZq4O4P9gZrj115f6sE2O7rDDdcGMSTqwJ3dUTgwHQAh2OWUVSL+SFHi/V1Kq3/Nt6nIlKorqorn3fvYKgAqzJnATKqm37wgTnsICkTDnWAj049WreX1IYfqGBcEMoge0+kfytpIOJqcEzEs="
  file: dist/js/keyman.min.js
  skip_cleanup: true
  on:
    repo: sj-js/keyman
    branch: master